name: Exploring Variable Secrets
on: 
  wokflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      uses: docker build -t docker.io/dockerUserName/imageName:latest

    - name: Docker Login
      uses: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}  
      
         
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7
      
    - name: List Repo files
      run: ls -kt